langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rake db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: fmLkenbjaMe7Mp0vVJSGv/XMyEAh1mCIcR7abG8hWAth9VMs19/fIHSxBoDLulJXFnvnbjQpZRB18pkq763krYMpW5rgp4tmrrhqy2ZSxDMER/uP8rk6LTnRXX+kfyR/k4/y71AewZ4zmPfZqDxsmTMLXW8ORsEvSuWFkNwsNNZSqiTMKKdh//332p+03Vfcn6OMkTAV7tARYwhOIGsxdKddlSieVkPMqJ1ZQoIhn1lHd07kd1bVmRA+1qZwDDnjjeKCT0G6vAxD4T5vxF/b6GkCihTsglV5TvWajI/MMTexB2ouKl4h6Eyb2CVueKV7FoKxVUdiUjYlHgfusIybtQra+ocnSjncJzq//7QCSyfgs5xEilesLH5qXqGnESWpPHIC/GpiSHzt6+TaYSH4u6oqo6ewUIRmOE7tZ2jBCqNF5YJNN6mxzoICFUfQq3cy6l+XD8V5nnyuoJxx385KWCYfw6NrRLgkrB3d8kaAh4cFsIUu5WTnf5iLe9jlCRdq/ZyJ95y7mwLN4dtZYZgmnxkwrnUA6b1MibgWFhW9QNMKKtOTBmQDjRVhLMVaOMAD/IL/kGw/QlXrdS3LCJ8WV4xMmkxi/BPImdrhFAS5Bi3A/g07XdCmEpT3YLJWRDluoWacWx7CX7rrsLmgBiCj+kLrLY9Wc03+jF6jUIE5/DI=
  app: sinatra_website
  on:
    repo: colintalex/sinatra_website
    branch: heroku
  skip_cleanup: 'true'
